'use strict'

module.exports = function(server) {
  console.log('!Running seeders')
  const Sign = server.models.Sign
  const Symptom = server.models.Symptom

  /**  Signs  **/
  const signs = [
    'Abasia',
    'Acantosis',
    'Acantosis nigricans',
    'Acolia',
    'Acropaquia',
    'Adiadococinesia',
    'Adipocira',
    'Alalia',
    'Alucinación',
    'Alucinosis alcohólica',
    'Ampolla',
    'Anasarca',
    'Anillo de Kayser-Fleischer',
    'Anisocoria',
    'Anuria',
    'Apnea',
    'Arruga',
    'Ataxia',
    'Atrofia muscular',
    'Borborigmo',
    'Bulto en el pecho',
    'Cálculo dental',
    'Callo',
    'Callo óseo',
    'Canicie',
    'Caquexia',
    'Cetonuria',
    'Tríada de Charcot',
    'Cilindros urinarios',
    'Clonus',
    'Coluria',
    'Comedón',
    'Confusión',
    'Convulsión febril',
    'Costra',
    'Crepitante',
    'Cromatolisis',
    'Diarrea',
    'Disfonía',
    'Dispraxia',
    'Ecolalia',
    'Edema',
    'Eflorescencia',
    'Emaciación',
    'Enfisema subcutáneo',
    'Epistaxis',
    'Equimosis',
    'Eritema',
    'Eritrodermia',
    'Escala ABCD²',
    'Escara',
    'Espasmo muscular',
    'Esplenomegalia',
    'Esputo',
    'Esputo hemoptoico',
    'Esteatopigia',
    'Estertor',
    'Eutimia',
    'Exantema',
    'Excoriación',
    'Exoftalmia',
    'Fiebre',
    'Fiebre de origen desconocido',
    'Fractura',
    'Frecuencia cardíaca',
    'Gingivorragia',
    'Gliosis',
    'Goma granulomatosa',
    'Gránulos de Schüffner',
    'Habla escandida',
    'Halitosis',
    'Hedor hepático',
    'Hematemesis',
    'Hematocele',
    'Hematoma',
    'Hematuria',
    'Hemoptisis',
    'Hemorragia',
    'Hemorragia digestiva baja',
    'Hemorragia gastrointestinal',
    'Hepatomegalia',
    'Hinchazón',
    'Hiperfosfatemia',
    'Hiperglucemia',
    'Hipertelorismo',
    'Hipo',
    'Hipocinesia',
    'Hipofosfatemia',
    'Hipoglucemia',
    'Hipoglucemia diabética',
    'Hiposalivación',
    'Escala de Hunt y Hess',
    'Ictericia',
    'Ideas de referencia',
    'Incontinencia afectiva',
    'Inflamación',
    'Macroglosia',
    'Mácula',
    'Maloclusión',
    'Manchas café con leche',
    'Maniobra de Finkelstein',
    'Metrorragia',
    'Midriasis',
    'Mioclono',
    'Miodesopsias',
    'Mioglobinuria',
    'Miosis',
    'Nictalopía',
    'Nicturia',
    'Nistagmo',
    'Nódulo',
    'Nódulo de Lisch',
    'Oftalmoplejia',
    'Ojo morado',
    'Ojo rojo',
    'Oliguria',
    'Organomegalia',
    'Osteopenia',
    'Ovillo neurofibrilar',
    'Palidez',
    'Palinopsia',
    'Pápula',
    'Patognomónico',
    'Pentada de Reynolds',
    'Petequia',
    'Piuria',
    'Polaquiuria',
    'Poliuria',
    'Posición de decorticación',
    'Posición de descerebración',
    'Poste de barbero',
    'Proteinuria',
    'Pterigium colli',
    'Punto de McBurney',
    'Síndrome purpúrico',
    'Pústula',
    'Quiste',
    'Rectorragia',
    'Reflujo hepatoyugular',
    'Respiración paradójica',
    'Rinorrea',
    'Ritidosis',
    'Sialorrea',
    'Signo de Blumberg',
    'Signo de Chvostek',
    'Signo de Comolli',
    'Signo de Dunphy',
    'Signo de Durkan',
    'Signo de Duroziez',
    'Signo de Forchheimer',
    'Signo de Leser-Trélat',
    'Signo de Litten',
    'Signo de Mulder',
    'Signo de Murphy',
    'Signo de Musset',
    'Signo de Nikolski',
    'Signo de Phalen',
    'Signo de Rivero-Carvallo',
    'Signo de Rovsing',
    'Signo de Tinel',
    'Signo de Trousseau',
    'Signo del psoas',
    'Signo del surco profundo',
    'Signos vitales',
    'Síndrome de Courvoisier-Terrier',
    'Sofoco',
    'Soplo',
    'Soplo cardíaco',
    'Soplo cardíaco funcional',
    'Soplo cardíaco sistólico',
    'Soplo de Austin Flint',
    'Taquicardia',
    'Telangiectasia',
    'Temblor',
    'Tiempo de tromboplastina parcial activado',
    'Tos',
    'Tos vómica',
    'Trastorno formal del pensamiento',
    'Úlcera',
    'Xerosis'
  ]

  signs.forEach(async sign => {
    const found = await Sign.find({ where: { name: sign } })
    if (found.length === 0) {
      Sign.create({
        name: sign
      })
    }
  })

  const symptoms = [
    'Diarrea',
    'Dificultad respiratoria',
    'Dificultades respiratorias en niños o lactantes',
    'Dolor en el abdomen de corta duración',
    'Dolor en el abdomen, largo plazo',
    'Dolor en el pecho en lactantes y niños',
    'Dolor en el pecho, agudo',
    'Dolor en el pecho, crónico',
    'Dolor en la parte baja de la espalda',
    'Dolores de cabeza',
    'Erupciones de cutáneas leves y otros cambios en el piel',
    'Fiebre',
    'Fiebre en lactantes y niños',
    'Hinchazón de la cara',
    'Hinchazón del cuello',
    'Náuseas y vómito',
    'Náuseas y vómito en lactantes y en niños',
    'Pérdida del cabello',
    'Problemas al orinar',
    'Problemas de audición',
    'Problemas de eliminación',
    'Problemas de eliminación en lactantes y niños',
    'Problemas de la boca',
    'Problemas de la boca en lactantes y niños',
    'Problemas de la cadera',
    'Problemas de la garganta',
    'Problemas de la mano, de la muñeca, o del brazo',
    'Problemas de las piernas',
    'Problemas de los dientes',
    'Problemas de los genitales en la mujer',
    'Problemas de los genitales en los hombres',
    'Problemas de los genitales femeninos',
    'Problemas de los genitales masculinos',
    'Problemas de los ojos',
    'Problemas de los pies',
    'Problemas de los tobillos',
    'Problemas de oído',
    'Problemas de rodilla',
    'Problemas del ciclo menstrual',
    'Problemas del cuello',
    'Problemas del hombro',
    'Problemas para alimentar a lactantes y niños',
    'Problemas relacionados con el tejido mamario en los hombres',
    'Problemas relacionados con los senos en las mujeres',
    'Resfriados y la gripe',
    'Tos'
  ]

  symptoms.forEach(async symptom => {
    const found = await Symptom.find({ where: { name: symptom } })
    if (found.length === 0) {
      Symptom.create({
        name: symptom
      })
    }
  })
}
